### PR TITLE
Fixed Moma to NET 4.5 and Cecil 0.9.6, important bugfixes

### PR DESCRIPTION
**Pull request by simonegli8**

### CODE REVIEW

**Comment by simonegli8** [comment]
This reuest is a followup of the closed request
https://github.com/mono/moma/pull/3
With important fixes. I've corrected the NET 4.5 assembly list, it should be correct now, and I've corrected the projects ToolsVersion's to 4.0 so they can also be opened in MonoDevelop

**Comment by simonegli8** [comment]
Hi, another fix set. I checked the other pull request back from 2011 that also updated to a newer Cecil, and I've seen there I did not do everything right, so I fixed it.

**Comment by marek-safar** [comment]
Could you fix the rebase conflicts

**Comment by simonegli8** [comment]
Hi, I don't know what a rebase conflict is. If I checkout moma/master locally and merge with my branch, no problems. I don't know what could be wrong. Of course, you've accepted the other pull request, and I had to do a merge with that pull request. But I think it should merge without problems now, no?

**Comment by marek-safar** [comment]
once you do the merge/rebase locally you still need to push the changes back to github

**Comment by simonegli8** [comment]
Hi, any progress on this? I got MoMA working here with the newest Mono version.

**Comment by marek-safar** [comment]
Had to merge it manually

**Pull request closed without merging**
